### PR TITLE
Add support for Github emoji characters

### PR DESCRIPTION
**Pull request by fdintino**
In Github feeds, emoji are converted from unicode to images hosted on Github. This commit uses a regular expression to replace these emoji with their equivalent unicode characters or, in cases where Github uses an emoji that doesn't map to unicode (e.g. `:shipit:`, :shipit:), it renders the emoji as `:emoji:`.

I'm not thrilled with how specific and fragile this regular expression is. I'm open to making it more flexible if you think that would help. Alternatively, I've added this functionality in another branch by adding javascript to Popover.html ([see here](https://github.com/fdintino/feeds/commit/10da1b62ebbec21e188f1bd0ca08890aab123df0)) in a way that is more general. If you would prefer, I can close this pull request and open that one. The only issue with that approach is that there is a very short delay (less than 0.5 seconds) in swapping out the hidden `` tags. I could also use the javascript approach to convert `:emoji:` references to unicode in text nodes if there is a desire for that functionality.

### CODE REVIEW

**Comment by fdintino** [comment]
An additional note: `NSRegularExpression` isn't added until 10.7, so if Feeds.app is still maintaining support for 10.6 I can wrap this code in an `#if` directive.

**Comment by lylo** [comment]
I think it would be nice to maintain 10.6 compatibility.

**Comment by fdintino** [comment]
In that case, I think it would be better to do this in Popover.html. I was able to fix the delay mentioned above, and I do a check for emoji unicode support so that 10.6 can fall back to `:emoji:`.

**Comment by nfarina** [comment]
This does seem to work... But I'm curious what the motivation was behind this ... when I compare the two styles, here's your version using "real emoji":

screen shot 2015-05-20 at 11 48 13 am

And here's the current image-based emoji:

screen shot 2015-05-20 at 11 48 27 am

It seems like they are pretty equivalent?

**Comment by fdintino** [comment]
Are you perhaps on Yosemite? I'm on Mavericks and those images don't come through.

**Comment by nfarina** [comment]
Yes I'm on Yosemite - but I believe it should work on any platform since I believe Github embeds these "imoji" using `` tags?

**Comment by fdintino** [comment]
yeah, I can't reproduce the original issue either anymore. Closing.

**Pull request closed without merging**
